export { default as AboutMe } from './AboutMe';
export { default as ContactMe } from './ContactMe';
export { default as Home } from './Home';
export { default as Footer } from './Footer';
export { default as Navbar } from './Navbar';
export { default as NotFound } from './NotFound';
export { default as Projects } from './Projects';
export { default as Recommendations } from './Recommendations';
export { default as Resume } from './Resume';
